### ISSUE TITLE
Problem when starting terminator

### ISSUE THREAD

**Issue by danielwerner-dev** [cvuorinen/dotfiles#2]
When im starting the terminator, some errors are showed on the screen:

compdef: unknown command or service: git-diff
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-checkout
compdef: unknown command or service: git-log
compdef: unknown command or service: git-push

I tryed to solve, in the file:  ~/.config/terminator/config without success, can anyone help me ?

**Comment by cvuorinen** [comment]
Sounds like it’s an issue with oh-my-zsh rather than terminator config.
Did you try googling with that error message and the suggestions in the first results? (Something about compaudit etc.)

**Comment by danielwerner-dev** [comment]
Yes, I tryed but all I did didn't help..
